### PR TITLE
Passing options to package install

### PR DESCRIPTION
**Pull request by nilroy**
Keeping the same configuration file while installing grafana in ubuntu

### CODE REVIEW

**Comment by nilroy** [comment]
@JonathanTron When are you planning to have a new version of this cookbook in supermarket?

**Comment by JonathanTron** [comment]
@nilroy Thanks for another fine PR. I plan to release a new 3.0 version in the coming two weeks.

**Comment by JonathanTron** [comment]
merged via https://github.com/JonathanTron/chef-grafana/commit/8c291ad4c1cc4601a2366ff4a271e55dd8828f75

**Comment by nilroy** [comment]
@JonathanTron Thats great :)

**Pull request closed without merging**
