### PR TITLE
Adding data dir to templates

### PR DESCRIPTION
**Pull request by lexh**
Adds `log_dir` and `data_dir` to templates. Ambling toward [#43](https://github.com/JonathanTron/chef-grafana/issues/43).

### CODE REVIEW

**Comment by lanyonm** [comment]
Thanks Lex!

Could you squash the commits so it's one change in git history?

**Comment by lexh** [comment]
Squashed!

**Comment by lanyonm** [comment]
:+1: Thanks!

**Comment by JonathanTron** [comment]
Thanks guys! :+1:

**Pull request merged**
