### PR TITLE
Move lwrp to real lwrp

### PR DESCRIPTION
**Pull request by kamaradclimber**
All resources and providers were defined by subclassing lwrpbase
classes. The lwrp dsl make it simpler.
With this change, the cookbook is compatible with chef 11 again

### CODE REVIEW

**Comment by JonathanTron** [comment]
Thanks, that's quite a nice PR. I'll review later and probably merge it.

**Comment by lanyonm** [comment]
The intention of building the resouces this way was to follow the emerging convention of resource-based cookbooks. I was following the [mysql cookbook](https://github.com/chef-cookbooks/mysql/tree/master/libraries), but as you pointed out, that method has it's deficiencies.

There's been discussion about how extending LWRPBase is incorrect and new resoucres and providers should extend the `Resource` and `Provider` classes. The [firewall cookbook](https://github.com/opscode-cookbooks/firewall/tree/master/libraries) implements this pattern as does some of @coderanger's work. I was hoping to get feedback via the mailing list on this, but haven't as of yet.

I wanted to make the major upgrade as future proof as possible, but it may be the case that the approach I took is not yet mature enough.

**Comment by JonathanTron** [comment]
@lanyonm I really would like to find a place where one or the other method is said to be the way to go. I have personally no preference for one over the other. The DSL one has less code, but it is less explicit than the subclass. 

@kamaradclimber Do you have any reason to prefer one over the other?

**Comment by kamaradclimber** [comment]
@lanyonm having a resource based cookbook does not prevent from using lwrp dsl or maybe I am missing something.
The current trend of writing library cookbooks make sense for techs that may have several instances per physical server, but I am not sure that grafana is such a project (and it supports multi organization now).

@JonathanTron lwrps are seems easier to read to me and are probably future proof (are compatible in chef >=10). I think this is really a matter of preference, mine goes to readable and documented (lwrps instead of hwrp).

**Comment by lanyonm** [comment]
I'm feeling less and less strongly about this because of the absence of feedback from the email list and hangops chef channel. If we don't hear anything today, let's merge this in tomorrow (Saturday).

**Pull request merged**
