### PR TITLE
improve user management

### LINKED ISSUE #82: ERROR: Endpoint not found when sending GET /api/admin/users
I am trying to add a user as such,

grafana_user 'person2' do
  port grafana_port
  full_name 'John Smith'
  email 'test@example.com'
  passwd 'test123'
  admin false
  action :create_if_missing
end

while processing, get_global_user_list() in libraries/user_api.rb gets called and there is a GET call to /api/admin/users. Peeking into the api docs, I don't see GET allowed for that endpoint, but there is something around api/users.

the following is the error I recieved. please help.

[2015-09-02T03:02:25+00:00] ERROR: Endpoint not found when sending GET /api/admin/users

```
       ================================================================================
       Error executing action `create_if_missing` on resource 'grafana_user[person2]'
       ================================================================================

       TypeError
       ---------
       no implicit conversion of String into Integer

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:27:in `[]'
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:27:in `block (2 levels) in class_from_file'
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:26:in `each'
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:26:in `block in class_from_file'

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/demo-grafana/recipes/default.rb

        32: grafana_user 'person2' do
        33:   port grafana_port
        34:   full_name 'John Smith'
        35:   email 'test@example.com'
        36:   passwd 'test123'
        37:   admin false
        38:   action :create_if_missing
        39: end

       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/demo-grafana/recipes/default.rb:32:in `from_file'

       grafana_user("person2") do
         action [:create_if_missing]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         declared_type :grafana_user
         cookbook_name "demo-grafana"
         recipe_name "default"
         port 8080
         full_name "John Smith"
         email "test@example.com"
         passwd "test123"
         host "localhost"
         user "admin"
         password "admin"
         login "person2"
         global true
       end


   Running handlers:
   [2015-09-02T03:02:25+00:00] ERROR: Running exception handlers
   Running handlers complete
   [2015-09-02T03:02:25+00:00] ERROR: Exception handlers complete
   Chef Client failed. 1 resources updated in 6.669768779 seconds
   [2015-09-02T03:02:25+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   [2015-09-02T03:02:25+00:00] ERROR: grafana_user[person2] (demo-grafana::default line 32) had an error: TypeError: no implicit conversion of String into Integer
   [2015-09-02T03:02:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### PR DESCRIPTION
**Pull request by jbfavre**
As described in #90 , user management in chef-grafana was lacking some useful features.
This PR aims to rewrite most of the user management provider to provide a consistent exprience with other providers as well as restore a working provider (this PR might closes #82 as well).

Please note that I do not manage user to organizations link. This will be implemented after the organization rewrite.

### CODE REVIEW

**Comment by lanyonm** [comment]
I think the tests are failing due to an old source url in the `Berksfile`. Could you update it in your PR?

``` ruby
source 'https://supermarket.chef.io'
```

Thanks.

**Comment by jbfavre** [comment]
Oh... OK. didn't touch that part. Will do
Got also an issue with Rubocop, because `libraries/user_api.rb` is longer that the 120 lines limits in `.rubocop.yml`.
Will try to fix it as well

**Comment by jbfavre** [comment]
don't know what to do. foodcritic & rubocop just run fine on my laptop :-/

**Comment by lanyonm** [comment]
We've been working on this internally for much of the afternoon and upgrading to Berkshelf 4.0.0 worked for us. Details here: https://twitter.com/kantrn/status/651211376451391488. It's been one of those days...

**Comment by JonathanTron** [comment]
@jbfavre it looks really great, don't worry too much about failing rubocop,I think the problem is the CI config with caching... I'll work it out.

**Comment by jbfavre** [comment]
@JonathanTron I just gave up on fixing CI :)
Fixing one error leads to another one :-/

BTW, all tests run fine on my laptop with latest chefdk version

**Pull request merged**
