### PR TITLE
[Breaking] All ini file is configured via attribute

### PR DESCRIPTION
**Pull request by kamaradclimber**
All ini file is now configured via attributes.
Format is simple (via section) and allow complex to introduce comments
and commented options.

Since grafana defaults are ok, only a few default params are configured
by default for demonstration purpose.

NB: I have included the commit present in my previous PR to be able to use this branch in my organization, feel free to cherry-pick if you want.

### CODE REVIEW

**Comment by JonathanTron** [comment]
Thanks for another great PR, I like the fact that the template is fully customizable via attributes. I've already merged it and extract a basic helper for the template logic in https://github.com/JonathanTron/chef-grafana/tree/grafana-2-ini-via-attributes.

I would like to see what @lanyonm think about it before merging it.

**Comment by lanyonm** [comment]
After thinking about it for a while, I like the idea of this approach. Using the `[section][key] = value` format is the way Grafana parses it's config, so it should be relatively future proof: https://github.com/grafana/grafana/blob/master/pkg/setting/setting.go.

It appears this implementation isn't quite complete though. For example, it renders something like this on converge:

```
[database]
# Either mysl, postgres, sqlite3, it's your choice
;sqlite3
127.0.0.1:3306
grafana
root
```

The issue is that each config line is missing the key and =, causing the service start to fail. I've added a spec test to illustrate this.

**Comment by kamaradclimber** [comment]
I'll fix it

On Sat, Jun 13, 2015 at 2:30 AM, Michael Lanyon notifications@github.com
wrote:

> After thinking about it for a while, I like the idea of this approach.
> Using the [section][key] = value format is the way Grafana parses it's
> config, so it should be relatively future proof:
> https://github.com/grafana/grafana/blob/master/pkg/setting/setting.go.
> 
> It appears this implementation isn't quite complete though. For example,
> it renders something like this on converge:
> 
> [database]
> 
> # Either mysl, postgres, sqlite3, it's your choice
> 
> ;sqlite3127.0.0.1:3306
> grafana
> root
> 
> The issue is that each config line is missing the key and =, causing the
> service start to fail. I've added a spec test to illustrate this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JonathanTron/chef-grafana/pull/56#issuecomment-111657789
> .

## 

Grégoire

**Comment by JonathanTron** [comment]
I've cherry picked and fixed the specs, thanks a lot Grégoire.

**Pull request closed without merging**
