### PR TITLE
 added amazon linux in kitchen test

### PR DESCRIPTION
**Pull request by thirumoorthir**
# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by xorima** [comment]
Hey @thirumoorthir 

Thanks for this, for testing to work you will need to add a definition to the `kitchen.dokken.yml` file, such as we have in `haproxy` here: https://github.com/sous-chefs/haproxy/blob/master/kitchen.dokken.yml#L51

You will also need to add the definitions to circleci, see: `.circleci/config.yml` you can copy and paste one of the groups for an OS and add the `amazonlinux2` to it

it looks like we currently have testing for amazon linux 1 only, I think it would be best to remove that and replace it with the amazon linux 2, what are your thoughts?

Thanks Again

Jason

**Review by xorima — CHANGES_REQUESTED** [review]
see comment

**Comment by xorima** [comment]
Hey @thirumoorthir 
grab me in slack on the sous-chefs channel when you have time and we can work together to get this in?

In the mean time we have migrated to github actions as well, sorry about that

**Review by xorima — CHANGES_REQUESTED** [review]
could you re-base this against master please, we recently migrated to github actions and are no longer using circleci, you will need to update the list things to test in the `.github/workflows/ci.yaml` file to cover amazonlinux-2

**Comment by xorima** [comment]
Hey @thirumoorthir 

Do you have time to work on this currently? If you need help drop by the #sous-chefs channel on slack :)

**Comment by thirumoorthir** [comment]
Will work on this and respond to you

Sent from my iPhone

On 11-Mar-2020, at 2:25 PM, Jason Field <notifications@github.com> wrote:

﻿

Hey @thirumoorthir<https://github.com/thirumoorthir>

Do you have time to work on this currently? If you need help drop by the #sous-chefs channel on slack :)

**Comment by tas50** [comment]
Can you rebase this and add the changes from #335?

**Comment by damacus** [comment]
Can you reopen a PR with the changes from this and #335 in the same PR, with the latest master. 

Thanks!

**Pull request closed without merging**
