### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ghost**
I been working on cleaning some stuff up in the cookbook and adding some more tests.

One notable change is, I changed the default location from /opt /srv/apps based on [FHS](http://www.pathname.com/fhs/). 

Just about everything else was test related or rubocop related.

### CODE REVIEW

**Comment by ghost** [comment]
I should also note I changed the default installation method to file. Using git master is probably a bit risky, a single commit could break things. I switched it over to use the file install_type by default so the cookbook can follow stable releases. Git is always there if someone actually needs it.

**Comment by JonathanTron** [comment]
Thanks for your hard work.

**Comment by ghost** [comment]
Thanks for the merge! :beers:

**Comment by arifcse019** [comment]
@gregf Can you please explain a little bit how installation path /opt violates FHS? I checked the relevant section in the document but could not find the answer

**Comment by ghost** [comment]
@arifcse019 My thoughts were based on what the definition of /srv says, which can be found [here](http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM)

Which basically says /srv is for site specific data including `www`, `rsync`, `ftp`, and `csv`. Since we are serving `www` data I felt /srv is where it belonged.

[opt](http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES) talks about configuration files and static binary packages. I don't see anything that mentions the type of files we're are storing here.

I'm open to other thoughts on the matter though, so let me know if I'm missing something.

**Comment by arifcse019** [comment]
Thanks and Disclaimer: I am not a pro in Unix system administration. Just trying to better understand why things are done in certain way.

So under FHS definition. /srv is for data but not the applications that serve those data about the sites hosted on the machine. What do you think?

**Comment by ghost** [comment]
@arifcse019 Sounds good

**Pull request merged**
