### PR TITLE
Update repo location to new grafana repos (Fixes #220)

### LINKED ISSUE #220: Grafana deb & rpm repos have moved
### Cookbook version
3.0.1

### Chef-client version
14.4.18

### Platform Details
Ubuntu

The [Grafana repositories have moved](https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/) and the packagecloud.io repos have been discontinued as of 7 Jan 2019.

I can file a PR for it if you wish, but i'm not sure how close to release the current master branch is. If that is not close to release yet i can file PR's against master and against v3.0.1 so you have the option of releasing a v3.0.2 in the meantime.

### PR DESCRIPTION
**Pull request by hrak**
### Description

This PR updates the repo settings to the new Grafana repository

### Issues Resolved

#220 

### Check List
- [X ] All tests pass. See https://github.com/sous-chefs/grafana/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by xorima — DISMISSED** [review]

**Comment by xorima** [comment]
@hrak can you add in a change log entry please, then merge 👍 

Thanks 
Xorima

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by SuperQ** [comment]
Looks like the changelog entry is ready.

**Review by xorima — APPROVED** [review]

**Comment by xorima** [comment]
Thanks 👍

**Pull request merged**
