### PR TITLE
Corrects the install type to 'file' instead of 'zipfile'

### PR DESCRIPTION
**Pull request by fhats**
Ran into this while switching back to the zipfile installation from a git installation. Looks like this attribute should be set to `file` instead of `zipfile`, so I updated the README to correct this.

Thanks for the cookbook :)

### CODE REVIEW

**Comment by ghost** [comment]
I switched this from .zip to the .tar.gz in one of my previous pull requests to avoid unzip needing to be installed by ark. It's my fault that this inconsistency exists.

Where you updated the documentation that mentions the `node['grafana']['zipfile_checksum']` attribute, we should probably just name this file_checksum to keep things consistent, and get rid of any references to zip files directly.

*_EDIT_ @fhats if you don't mind could you fix your pull request to fix the overall problem? If not I can take a stab at this.

**Comment by JonathanTron** [comment]
Thanks @fhats for the fix and thanks @gregf for the follow-up. I will merge this pull-request and rename the `zipfile_checksum` attribute README.

**Comment by fhats** [comment]
@gregf I'm happy to change it to `file` everywhere; I thought about it but didn't really mind the inconsistency, so long as it is documented.

Up to @JonathanTron, I suppose. He didn't really seem too bothered :)

**Comment by JonathanTron** [comment]
I've already updated the remaining references to `zipfile`. Thanks again for the fix.

**Pull request merged**
