### PR TITLE
change nginx cookbook to chef_nginx

### PR DESCRIPTION
**Pull request by runningman84**
see https://github.com/JonathanTron/chef-grafana/issues/148

### CODE REVIEW

**Comment by dpattmann** [comment]
Hi @runningman84,

I get the following error when using your branch.

```
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/chef_nginx/definitions/nginx_site.rb:

          19:  # limitations under the License.
          20:  #
          21:  
          22:  define :nginx_site, enable: true, timing: :delayed do
          23:    if params[:enable]
          24:  
          25:      template "#{node['nginx']['dir']}/sites-available/#{params[:name]}" do
          26>>       source params[:template]
          27:        variables(params[:variables])
          28:        only_if { params[:template] }
          29:      end
          30:  
          31:      execute "nxensite #{params[:name]}" do
          32:        command "#{node['nginx']['script_dir']}/nxensite #{params[:name]}"
          33:        notifies :reload, 'service[nginx]', params[:timing]
          34:        not_if do
          35:          ::File.symlink?("#{node['nginx']['dir']}/sites-enabled/#{params[:name]}") ||

         Platform:
         ---------
         x86_64-linux
```

I think we have to remove `template false` from https://github.com/runningman84/chef-grafana/blob/runningman84-change_nginx_cookbook/recipes/_nginx.rb#L39-L41

Best regards,
Dennis

**Comment by runningman84** [comment]
@dpattmann thanks four your help!

**Comment by bradenwright** [comment]
What's the status on this?  It's working well for me, it would be nice to get it merged in

**Comment by runningman84** [comment]
@JonathanTron what do you think?

**Comment by JonathanTron** [comment]
Hi @runningman84, sorry for being so late on this front. 

Thanks a lot for the PR, could you split the grafana version update in a separate PR? Then I'll merge the nginx update right away.

**Comment by akadoya** [comment]
we're facing the same exact issue and found out that Berksfile is also needed to be updated.
as we really need this to be merged soon, I have opened new PR as #153 only for this nginx dependency update.

**Comment by JonathanTron** [comment]
Fixed by merging #153, thanks @runningman84 and @akadoya for your work!

**Pull request closed without merging**
