### PR TITLE
Feat improve datasource provider

### PR DESCRIPTION
**Pull request by jbfavre**
Same work as for organization & user :)

### CODE REVIEW

**Comment by JonathanTron** [comment]
And another one :+1:

**Comment by jbfavre** [comment]
@JonathanTron last one, dashboard, is in progress :)

**Comment by lanyonm** [comment]
Hi @jbfavre,
With this change is there an equivalent to the existing `:create` behavior where `grafana_datasource` can be defined and kept updated with a single action? I'm not a native Rubyist, but I can't see how to accomplish this with these changes.

Thanks,
Mike

**Comment by jbfavre** [comment]
Hello @lanyonm 
I will have a look at it, maybe tomorrow.

**Pull request merged**
