### PR TITLE
Adds an `include_repo` boolean property to install resource

### PR DESCRIPTION
**Pull request by ngharo**
Some users have external repository management infrastructure and prefer
that cookbooks don't manage repos at all. For instance: an air-gapped
environment with a Red Hat Satellite server providing yum content.

## Check List

- [ ] All tests pass. See TESTING.md for details
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ngharo** [comment]
Should I be bumping the version?

**Comment by xorima** [comment]
Hi @ngharo 

Regarding the version bump, please do not change the version, I will handle that as a maintainer :)

Thank you for the pr, I am trying to understand the usecase for this, 
The install resource is separate so you could just install grafana in your wrapper cookbook and use the resources for management, if you disable the repo management all you are essentially running is: 
```
    package 'grafana' do
      version new_resource.version if new_resource.version
    end
```
I feel this is easy enough to just add in a wrapper?

Your thoughts and feedback would be appreciated, 

Thanks 

Xorima

**Comment by ngharo** [comment]
@Xorima that's a good point.

I describe my use case (airgapped environment) in the OP. I can definitely do as you suggest. I'm just used to seeing the ability to skip the repo creation in most upstream cookbooks I use.

I modeled this change after the install resource of the [InfluxDB](https://github.com/bdangit/chef-influxdb) and [Telegraf](https://github.com/NorthPage/telegraf-cookbook) cookbooks

**Comment by xorima** [comment]
Hi @ngharo I will be closing this in line with the discussion above, however thanks for raising it :+1:

**Pull request closed without merging**
