### PR TITLE
fix wrong naming in log.file section in grafana.ini.erb template

### PR DESCRIPTION
**Pull request by chivunito**
# Description
log.file section had duplicated format keys preventing to configure Grafana file logging

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by damacus — DISMISSED** [review]
Looks like you've got a bit of markdown needing fixing. BUt LGTM when that's fixed

**Comment by damacus** [comment]
FYI, I've tagged this for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by damacus** [comment]
Can you rebase and fix the merge conflicts please? I've just merged a pretty hefty PR into main.

**Comment by chivunito** [comment]
Sorry @damacus, as you can see, I'm still a noob with git (this is my first PR) ! (I merged another fork), I'll try to find my way

**Comment by ramereth** [comment]
> Sorry @damacus, as you can see, I'm still a noob with git (this is my first PR) ! (I merged another fork), I'll try to find my way

Let us know if you need some help

**Comment by bmhughes** [comment]
This PR doesn't apply any more as the problem it's addressing should be covered by the refactor in v10, the ERB template is just a placeholder now for a method that generates the config file hence the merge conflict with the template file.

**Comment by ramereth** [comment]
@chivunito can you please confirm that the latest release resolves the original issue this PR was addressing? If it is fixed, then please close this PR. Thanks!

**Comment by chivunito** [comment]
Thanks for the refactoring, indeed, that solved the issue ! Thanks for your help and support !

**Pull request closed without merging**
