### PR TITLE
Test if any org exist

### PR DESCRIPTION
**Pull request by HelioCampos**
When we want to create and/or create an organization it does not necessarily already has any organization already created. We need to test an array before iterate over it.

### CODE REVIEW

**Comment by JonathanTron** [comment]
Thanks for the PR, but I don't get what you're trying to achieve, `orgs.each` will not do anything if the `orgs` variable is empty, checking `orgs.any?` doesn't do anything more than the default of `.each`.

**Comment by JonathanTron** [comment]
Ok I think I get it, the `get_orgs_list` method can return an array _or_ `nil` in case of failure to connect to the server. I think you want to use `if orgs` instead of `if orgs.any?` the later will fail on `nil`.

**Comment by HelioCampos** [comment]
Hi Jonathan,
- The function get_orgs_list does not return an empty array when there's not org. Maybe the problem could be solved returning an empty array. What do you think?

Regards,

**Comment by JonathanTron** [comment]
Yes you're right the return value being different is a problem, would you please try to change it? Maybe take extra care if the return value `nil` was not used to _badly_ detect a connection error somewhere.

**Comment by HelioCampos** [comment]
ok

**Pull request closed without merging**
