### PR TITLE
Attempting to install file only if it is downloaded and/or modified

### PR DESCRIPTION
**Pull request by arifcse019**

### CODE REVIEW

**Comment by arifcse019** [comment]
Solves issue https://github.com/JonathanTron/chef-grafana/issues/72

**Comment by JonathanTron** [comment]
Hi @arifcse019, thanks for the PR, it's indeed always a chicken and egg problem with downloaded resources and installation. 

Here's a scenario I've encountered a lot, let's say we've downloaded the file but chef run was kill afterwards, then we already have the file, on the next run `package_file.updated_by_last_action?` will be false and we will not install it at all.
Now I understand your problem, because it's also something I've encountered a number of time.

About the `only_if { package_file.updated_by_last_action? }` I would prefer a `notifies :install, "dpkg_package[grafana-#{node['grafana']['version']}], :immediately"`.

This would cover the `install when file has been downloaded`, but not the `install also if file has been downloaded but not installed by last run`. For this, we could tackle it by adding a guard like you did, but on the downloaded file existance: `only_if { File.exist? "#{node['grafana']['file']['url']}_#{node['grafana']['version']}_amd64.deb" }`.

What do you think?

**Comment by arifcse019** [comment]
Sounds like a really good idea. I am going to give it a try and report back

**Comment by arifcse019** [comment]
On a second thought, I am not sure if the solution above will prevent chef from installing the package even if the package is already installed. I think repeating the same guard for both downloading and installation is the best way. 

I have captured the guard string in a separate variable such that we do not have to update it in two places if needed

**Comment by JonathanTron** [comment]
Hello @arifcse019, thanks for your work and your thoughts on this issue, I've merged your commits and switch back to remote_file to `action :create` adding the package checksum.

It's a little more work when changing the Grafana version, but I've found it's the best way to prevent all kind of problems (file re-download, partial file, wrong file, etc).

Thanks again for your participation!

**Comment by arifcse019** [comment]
My pleasure and pride to be a contributor. Thank you!

**Pull request merged**
