### PR TITLE
chef-client 14 freezes the new_resource hash

### PR DESCRIPTION
**Pull request by eschro-illumio**
### Description

This fix makes the cookbook compatible with chef-client 14 (and maybe _more_ compatible with 13?). (Pretty sure it's related to [this chef 13 release note](https://docs.chef.io/release_notes.html#default-values-for-resource-properties-are-frozen) about the immutability of new_resource properties.

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/grafana/blob/master/TESTING.md - this link should be updated to point to the [section in README.md](https://github.com/sous-chefs/grafana/#testing).
- [ ] ~~New functionality includes testing.~~ (not applicable)
- [ ] ~~New functionality has been documented in the README if applicable~~ (not applicable)

### Testing

Tests were performed using ChefDK 3.0.36. While I'm *mostly* confident my patch works, this [cookbook hasn't passed tests in ~3 months](https://travis-ci.org/sous-chefs/grafana/builds), and running kitchen-vagrant and kitchen-dokken tests on my own failed for different reasons, unrelated to my patch. I don't have the spare cycles to hunt it all down right now, so if someone beats me to the punch, I will happily re-base and test.

```
-- cookbooks/grafana ‹eschro/v3-chef-14› » chef --version
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72
-- cookbooks/grafana ‹eschro/v3-chef-14› » foodcritic -X spec -f any ./
Checking 31 files
...............................

-- cookbooks/grafana ‹eschro/v3-chef-14› » rspec
...................................................................................................................WARNING: you must specify a 'platform' and 'version' to your ChefSpec Runner and/or Fauxhai constructor, in the future
omitting these will become a hard error. A list of available platforms is available at https://github.com/chefspec/fauxhai/blob/master/PLATFORMS.md
.

Finished in 18.7 seconds (files took 6.17 seconds to load)
116 examples, 0 failures

-- cookbooks/grafana ‹eschro/v3-chef-14› »
```

### CODE REVIEW

**Comment by damacus** [comment]
Hey, 

thanks for the contribution! 

can you run cookstyle over this please? CI is setup to fail on style first, before spending time doing the integration tests.

**Comment by eschro-illumio** [comment]
I made the changes to appease cookstyle, but it looks like [something else is missing for the CI runs](https://travis-ci.org/sous-chefs/grafana/jobs/400982332)

**Comment by eschro-illumio** [comment]
[note: I updated my original comment to make it more clear that I did attempt the kitchen-vagrant and kitchen-dokken tests on my own.]

**Comment by damacus** [comment]
I'm going to test this, today. I'm pretty sure I'm going to remove the danger file portion from Travis as Travis is being a little difficult with that config (it always breaks)

**Comment by abilun** [comment]
@damacus, gentle ping. Have you test it yet?

**Comment by damacus** [comment]
I think we need to get the rest of the cookbook passing and less mad before we can get this sensible fix in.

**Comment by dschlenk** [comment]
Voting for this patch as I ran into the same issue trying to delete a datasource with Chef 14

**Comment by xorima** [comment]
Hi @eschro-illumio 

Thank you for the PR, I am currently re-writing the cookbook to use resources, so there is a good chance this won't be directly merged, however I will be taking the changes made on board during the rewrite, when I am finished I will come back and get you to confirm that your issue is fixed if that is ok?

Thanks!

**Comment by xorima** [comment]
Closing as merged #216

**Pull request closed without merging**
