### PR TITLE
Add config resource for rendering service

### PR DESCRIPTION
**Pull request by infertux**
# Description

Add in support for configuring rendering service

https://grafana.com/docs/grafana/latest/installation/configuration/#rendering

## Issues Resolved

N/A

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing. **N/A: similar resources don't have tests**
- [x] New functionality has been documented in the README if applicable.

PS: I didn't bump the cookbook version in `metadata.rb` in case you want to add more changes before the next release.

### CODE REVIEW

**Review by xorima — COMMENTED** [review]
Looks good, can you fix up the mdl error?

**Comment by infertux** [comment]
@Xorima Done.

**Comment by xorima** [comment]
Released as 8.8.0

**Comment by infertux** [comment]
@Xorima Awesome, thanks!

**Pull request merged**
