### PR TITLE
Add config_unified_alerting_screenshots resource

### PR DESCRIPTION
**Pull request by PovilasV1**
# Description

Add `config_unified_alerting_screenshots` resource

## Issues Resolved

n/a

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by bmhughes** [comment]
Thanks for this @PovilasV1, looks great!

If you wouldn't mind fixing the markdown link check so the rest of the CI suite runs we can get this released.

**Comment by LukoJy3D** [comment]
Hey 👋 doesn't this check run only on markdows existing in main?

**Comment by bmhughes** [comment]
The action is checking against the PR branch but as the links aren't relative and point to `main` it will always fail, relative links **should** fix it.

**Comment by PovilasV1** [comment]
Updated the links.

**Comment by bmhughes** [comment]
Spot on, thank you @PovilasV1

**Review by bmhughes — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [10.5.0](https://github.com/sous-chefs/grafana/releases/tag/10.5.0)

**Comment by xorima** [comment]
@bmhughes fyi links were full and not relative because supermarket doesn't support relative links :( https://supermarket.chef.io/cookbooks/grafana

not sure what the real fix here should be ...

**Pull request merged**
